extends SceneTree

# Emits the fixture that pins docs/terrain-choice-core.js to the engine.
#
# The core predicts, from your TileSet alone, which neighbourhood every cell of a
# painted region asks for — and the web page and CLI act on that. A predictor
# that drifts from the engine is worse than no predictor, so the numbers it must
# reproduce are not typed by hand here: they are read out of Godot.
#
#   godot --headless --path tools/godot-test --script res://dump_terrain_paint_fixtures.gd
#     > addon/docs/terrain-paint-fixtures.json
#
# test/web-terrain.test.js reads the result and fails if the core disagrees on a
# single cell. Regenerate it against a newer Godot and the test tells you whether
# terrain painting changed.

const PAIRS := [
	[1, TileSet.CELL_NEIGHBOR_TOP_SIDE],
	[2, TileSet.CELL_NEIGHBOR_TOP_RIGHT_CORNER],
	[4, TileSet.CELL_NEIGHBOR_RIGHT_SIDE],
	[8, TileSet.CELL_NEIGHBOR_BOTTOM_RIGHT_CORNER],
	[16, TileSet.CELL_NEIGHBOR_BOTTOM_SIDE],
	[32, TileSet.CELL_NEIGHBOR_BOTTOM_LEFT_CORNER],
	[64, TileSet.CELL_NEIGHBOR_LEFT_SIDE],
	[128, TileSet.CELL_NEIGHBOR_TOP_LEFT_CORNER],
]

func valid_bits(ts: TileSet) -> int:
	match ts.get_terrain_set_mode(0):
		TileSet.TERRAIN_MODE_MATCH_CORNERS_AND_SIDES: return 255
		TileSet.TERRAIN_MODE_MATCH_CORNERS: return 2 | 8 | 32 | 128
		TileSet.TERRAIN_MODE_MATCH_SIDES: return 1 | 4 | 16 | 64
	return 255

func mask_from(ts: TileSet, td: TileData) -> int:
	var ok := valid_bits(ts)
	var m := 0
	for p in PAIRS:
		if not (ok & int(p[0])):
			continue
		if td.get_terrain_peering_bit(int(p[1])) == 0:
			m |= int(p[0])
	return m

func mask_of(layer: TileMapLayer, at: Vector2i) -> int:
	var td := layer.get_cell_tile_data(at)
	return -1 if td == null else mask_from(layer.tile_set, td)

func rect_cells(w: int, h: int) -> Array[Vector2i]:
	var c: Array[Vector2i] = []
	for y in range(h):
		for x in range(w):
			c.append(Vector2i(x, y))
	return c

func paint(ts: TileSet, cells: Array[Vector2i]) -> TileMapLayer:
	var layer := TileMapLayer.new()
	layer.tile_set = ts
	root.add_child(layer)
	layer.set_cells_terrain_connect(cells, 0, 0, false)
	return layer

func region(ts: TileSet, w: int, h: int) -> Array:
	var l := paint(ts, rect_cells(w, h))
	var out := []
	for y in range(h):
		for x in range(w):
			out.append({"x": x, "y": y, "mask": mask_of(l, Vector2i(x, y))})
	l.queue_free()
	return out

# The chunked case (T9): paint the left half, record it, then paint the right
# half onto the SAME layer and record what the left half became.
func chunked(ts: TileSet, w: int, h: int) -> Dictionary:
	var half := int(ceil(float(w) / 2.0))
	var a: Array[Vector2i] = []
	var b: Array[Vector2i] = []
	for y in range(h):
		for x in range(w):
			if x < half:
				a.append(Vector2i(x, y))
			else:
				b.append(Vector2i(x, y))
	var layer := TileMapLayer.new()
	layer.tile_set = ts
	root.add_child(layer)
	layer.set_cells_terrain_connect(a, 0, 0, false)
	var before := []
	for c in a:
		before.append({"x": c.x, "y": c.y, "mask": mask_of(layer, c)})
	layer.set_cells_terrain_connect(b, 0, 0, false)
	var after := []
	for c in a:
		after.append({"x": c.x, "y": c.y, "mask": mask_of(layer, c)})
	layer.queue_free()
	return {"half": half, "before": before, "after": after}

func _init() -> void:
	var out := {
		"godot": Engine.get_version_info()["string"],
		"note": "generated by tools/godot-test/dump_terrain_paint_fixtures.gd — do not hand-edit",
		"sets": [],
	}
	for entry in [
		{"path": "res://tiles/blobsmith_tileset.tres", "name": "blobsmith_tileset.tres"},
		{"path": "res://tiles/sides16.tres", "name": "sides16.tres"},
	]:
		if not ResourceLoader.exists(entry["path"]):
			continue
		var ts: TileSet = ResourceLoader.load(entry["path"], "", ResourceLoader.CACHE_MODE_IGNORE_DEEP)
		var regions := []
		for wh in [[1, 1], [2, 2], [3, 3], [5, 3], [4, 2], [6, 4]]:
			regions.append({
				"w": wh[0], "h": wh[1],
				"cells": region(ts, int(wh[0]), int(wh[1])),
				"chunked": chunked(ts, int(wh[0]), int(wh[1])),
			})
		out["sets"].append({
			"name": entry["name"],
			"mode": ts.get_terrain_set_mode(0),
			"regions": regions,
		})
	print(JSON.stringify(out, "  "))
	quit(0)
